name: NYIAEE
favicon: null
layout_spectrum: 0.06721308827400208
typography_spectrum: 0.9265174355823547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.10454610036686063
  lightness: 0.1320250655990094
  saturation: 0.27370681217871606
  rhythmicContrast: 0.18967292341403663
purpose: []
